### ISSUE TITLE
"Can't find library ..." errors

### ISSUE THREAD

**Issue by Fuco1** [emacs-eask/cli#11]
When running `eask install-deps --dev` for smartparens, I get a lot of "can't find library" errors, see the screenshot

![image](https://user-images.githubusercontent.com/2664959/170264092-29a3406d-1a17-4423-8684-6aaf52b99986.png)

My Eask file based on the Cask file.

```
(package "smartparens" "1.11.0"
         "Automatic insertion, wrapping and paredit-like navigation with user defined pairs.")

(package-file "smartparens.el")

(source "gnu")
(source "melpa")

(depends-on "cl-lib" "0.3")
(depends-on "dash" "2.13.0")

(development
  (depends-on "f")
  (depends-on "ert-runner")
  (depends-on "undercover")
  (depends-on "shut-up")
  (depends-on "racket-mode")
  (depends-on "scala-mode")
  (depends-on "rust-mode")
  (depends-on "swift-mode")
  (depends-on "auctex")
  (depends-on "clojure-mode")
  (depends-on "lua-mode")
  (depends-on "js2-mode")
  (depends-on "ess")
  (depends-on "tuareg")
  (depends-on "elixir-mode")
  (depends-on "haskell-mode")
  (depends-on "markdown-mode")
  (depends-on "hungry-delete")
  (depends-on "evil")
  (depends-on "crystal-mode"))
```

**Comment by Fuco1** [comment]
I'm one of those dinosaurs still on E26 :sweat_smile: I should just take the hit and update one of these days.

**Comment by jcs090218** [comment]
This seems like an Emacs bug (design wise) to me since it get ignored after Emacs 28.1+ and it does not broke anything (from what I've discovered). We can hack Eask so it would stop reporting this error, but I think it's better to leave it as is it? 😕 

Any suggestions are welcome! :)

**Comment by Fuco1** [comment]
I'm wondering if this can cause issues in the CI pipelines with older emacs versions? otherwise I think yea we can close it.

**Comment by jcs090218** [comment]
I don't think it causes any issues, but it will report a bunch of "Can't find library" for sure.

Let me pin this issue, and hope people who use older versions of Emacs can see this thread once they have encountered it! :D
