### ISSUE TITLE
CLI is not parsing quoted args properly

### ISSUE THREAD

**Issue by Fuco1** [emacs-eask/cli#128]
A quoted argument should be treated as a single token, it seems eask is splitting on space "naively"

The same command works with `cask`

    eask exec buttercup -L . -L tests -p "should return bool if it is not surely non-eq to the other arg"

![image](https://user-images.githubusercontent.com/2664959/221374904-88c5b1a7-a269-4fbe-973f-a21d72ac43e0.png)

**Comment by jcs090218** [comment]
I've open a fix in #129.

I was hoping there is an built-in solution, but I could not find one. :P

**Comment by jcs090218** [comment]
It should be working now! Let me know if it works!

**Comment by Fuco1** [comment]
Pulled the latest master and it works indeed.  Thanks!
