### ISSUE TITLE
package-lint seems to exit after first issue is found

### ISSUE THREAD

**Issue by Fuco1** [emacs-eask/cli#134]
![image](https://user-images.githubusercontent.com/2664959/222732544-1faaaa84-f607-40e0-8be8-c6e75f3de832.png)

**Comment by jcs090218** [comment]
Yeah, this is the design. If you want to lint through and see all errors you would have to add `--allow-error` flag.

**Comment by Fuco1** [comment]
Wouldn't it be better to list all errors by default?  That's how most lint tools operate.

Also, now it looks like eask itself crashed, with the util.js error being shown.  That's what confused me.

**Comment by jcs090218** [comment]
I guess there are two issues here?

1. Change default to lint through all errors
2. Exit process silently without printing node's stacktrace

I've opened a PR in #136 for (Pt. 2). I will work on (Pt. 1).

**Comment by jcs090218** [comment]
Okay, everything are applied to the master branch! Can you test to see if it works? :)

**Comment by Fuco1** [comment]
Yea it's much nicer now.  The `throw` in the javascript was really annoying :)
