### ISSUE TITLE
Can I use Eask with different Emacs versions?

### ISSUE THREAD

**Issue by Fuco1** [emacs-eask/cli#143]
Eask minimal Emacs version is 26.1 while Elsa needs 26.3.  I would still like to test smartparens on 26.1 and 26.2, but now installation fails because Elsa can't install.

Is there some way to install some dependencies only for specific Emacs version?  I think this would be also a good candidate to add to the documentation if it's possible.

**Comment by jcs090218** [comment]
You can specify `Eask.26.1` and `Eask.26.2`, is this what you want? Or, you could do:

```elisp
(when (version< emacs-version "26.0")
  (depends-on "package-name"))
```

I think this will work?

**Comment by Fuco1** [comment]
will it also work inside the development block?  Not sure how the DSL is expanded/processed.

**Comment by jcs090218** [comment]
It wasn't working because of the `nil` value. But now it works after #144! :)

**Comment by jcs090218** [comment]
> Is there some way to install some dependencies only for specific Emacs version? I think this would be also a good candidate to add to the documentation if it's possible.

Yeah, documentation has always been my biggest problem. I try document things down, but often not very good. 😅 Feel free to open PRs for documentation, etc.

**Comment by jcs090218** [comment]
I think this is resolved; therefore, close it. ;)
