### ISSUE TITLE
Does not work on mac m1

### ISSUE THREAD

**Issue by hhamud** [emacs-eask/cli#179]
I get this error when trying to install and use it
```bash
user@Users-Laptop ~ % npm install -g @emacs-eask/cli


added 17 packages, and audited 18 packages in 4s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
user@Users-Laptop ~ %  eask --version
zsh: killed     eask --version
user@Users-Laptop ~ % 
```

Also tried out the native install using this
$ curl -fsSL https://raw.githubusercontent.com/emacs-eask/cli/master/webinstall/install.sh | sh

but that also does not work.

**Comment by jcs090218** [comment]
Hmmm... interesting. Can you try download the binary from our [release page](https://github.com/emacs-eask/cli/releases)? Or from the [snapshot repo](https://github.com/emacs-eask/binaries).

**Comment by hhamud** [comment]
> Hmmm... interesting. Can you try download the binary from our [release page](https://github.com/emacs-eask/cli/releases)? Or from the [snapshot repo](https://github.com/emacs-eask/binaries).
> 
> **Edit:** Can it be the zsh issue? See [this](https://stackoverflow.com/questions/66119081/why-does-zsh-kills-my-process-every-time-i-enter-a-git-command) stackoverflow. Sorry I don't use zsh, so I am just guessing here.

I still have the same issue with bash and when I downloaded the release binary for arm64 macos, I made it executable and then tried to execute it as so and it also failed.

```bash
user@Users-Laptop eask_0.8.1_macos-arm64 % chmod +x eask 
user@Users-Laptop eask_0.8.1_macos-arm64 % ./eask 
zsh: killed     ./eask
user@Users-Laptop eask_0.8.1_macos-arm64 % ./eask --help
zsh: killed     ./eask --help
user@Users-Laptop eask_0.8.1_macos-arm64 % 
```

**Comment by jcs090218** [comment]
Can you try without using the zsh? It seems like there are issues between macOS m1 and Node.JS (Eask is built on top of the NodeJS). Hopefully, it will give us more information regarding the "kill" error.

**Comment by jcs090218** [comment]
Thank you for testing it out! Did you install node using the nvm? It seems like that's the best solution for mac m1.

See https://www.youtube.com/watch?v=5jmtF6qpWq8&t=19s&ab_channel=TechFewSteps.

**Comment by hhamud** [comment]
> Thank you for testing it out! Did you install node using the nvm? It seems like that's the best solution for mac m1.
> 
> See https://www.youtube.com/watch?v=5jmtF6qpWq8&t=19s&ab_channel=TechFewSteps.

Thanks for the reply.

I already have node installed and I am using v18.

Macos isn't giving me any additional information so I am not even sure what I am doing wrong.

**Comment by hhamud** [comment]
Ok I found my problem.

I had to do a clean install, (remove the old eask in .local/bin) and then install using the node version.

and that managed to solve my problem.

Thanks for the help though, very much appreciated.

**Comment by jcs090218** [comment]
Awesome! I am glad you figured it out! 🚀 😁
