### ISSUE TITLE
eask in combination with windows-latest fails

### ISSUE THREAD

**Issue by sebastiaanspeck** [emacs-eask/cli#224]
In multiple examples the docs refers to, running eask with windows-latest, it results in the same error:

```
Run make ci
eask clean all
Can't read whole string
make: *** [Makefile:33: clean] Error 1
Error: Process completed with exit code 1.
```

E.g. https://github.com/emacs-lsp/lsp-mode/actions/workflows/test.yml?query=branch%3Amaster

**Comment by jcs090218** [comment]
The issue is the Emacs snapshot itself. The bug has already been fixed from the upstream, but they didn't release a new snapshot. Emacs dev doesn't release windows snapshots that often, and it hasn't been updated for a year (the last update is April 2023).

**Comment by jcs090218** [comment]
The windows snapshot has been updated today, and confirmed this error is gone now!
