### ISSUE TITLE
Release 0.9.7 is missing package-lock.json

### ISSUE THREAD

**Issue by piotrkwiecinski** [emacs-eask/cli#252]
Hi @jcs090218,
I was trying to update a nix package for the CLI, but the release is missing package-lock.json.
Any chance you could include it in the upcoming release?

It was removed in https://github.com/emacs-eask/cli/pull/218

**Comment by jcs090218** [comment]
Oh sorry. I didn't know it was used in the Nix package. I'll add it ASAP when the PC is available. 😔

**Comment by jcs090218** [comment]
Added the `package-lock.json` file back in 1ff49ac7307e98b49279f4a0fb8213a985adef8a. :)

**Comment by piotrkwiecinski** [comment]
Awesome thank you @jcs090218

**Comment by piotrkwiecinski** [comment]
@jcs090218 if possible would you be able to cut a 7.5.1 release with the included lock?

**Comment by jcs090218** [comment]
I have cut a release `0.9.8`; does that work for you? 🤔

**Comment by piotrkwiecinski** [comment]
@jcs090218 no it doesn't. The source code tar.gz appears to have a code from Apr 15. Not the latest one and it doesn't have package-lock.json. Sorry for causing a pain.

**Comment by piotrkwiecinski** [comment]
I reckon it's because the tag was created on April 15th and it's used as an archive.

**Comment by jcs090218** [comment]
I assumed `0.9.8` doesn't contain the package-lock.json file. Should I cut one more release? 🤔

**Comment by piotrkwiecinski** [comment]
@jcs090218 yes please. It doesn't because you created a tag on April 15th. It's when the archive is created not when you create a release. At least at the moment. Have a look at timestamps of files in the release notes.

**Comment by jcs090218** [comment]
I got it! I've published a new release, 0.9.9. It should contain a `package-lock.json` file.

**Comment by piotrkwiecinski** [comment]
@jcs090218 thank you builds with the tag :tada:
