### ISSUE TITLE
Use Deno instead of the Node.js?

### ISSUE THREAD

**Issue by jcs090218** [emacs-eask/cli#56]
Deno seems like a better alternative than Node.js, and [yargs]() also supports it!

**Comment by Fuco1** [comment]
If this means users would need to install Deno locally, I think it's a bit too early.  Its adoption is not that significant, whereas getting node.js with nvm is trivial these days (a one liner).

**Comment by jcs090218** [comment]
Yeah, I agree. The more I think about this, I feel like this isn't the right direction to approach.

Let me close this issue now and see what happens in the future!
